name: "GPG Sign"
description: "Use GPG to sign some artifacts"
author: chevdor
branding:
  icon: "umbrella"
  color: "blue"

inputs:
  key:
    description: >
      GPG Private Key
    required: true

  file:
    description: >
      The file to sign
    required: true

# outputs:
  # json:
  #   description: >
  #     Bla
    # value: ${{ steps.build.outputs.json }}

runs:
  using: "composite"
  steps:
    - name: Install Tooling
      shell: bash
      run: |
        gpg --version

    - name: GPG Sign Artifact
      id: gpg_sign
      shell: bash
      env:
        GPG_PRIVATE_KEY: ${{ inputs.key }}
        FILE: ${{ inputs.file }}
      run: |

        echo "TEST"

        # import private key
        echo "::group::Import Key"
        echo "Import private key"
        echo "$GPG_PRIVATE_KEY" | gpg --import

        # show list of keys
        echo "Show keys"
        gpg -K
        echo "::endgroup::"

        # sign artifact
        echo "::group::Signature"
        echo "Sign artifact"
        gpg --clearsign "${FILE}"

        # show signature
        echo "Show signature"
        sig_file="${FILE}.asc"
        echo "Signature file: ${sig_file}"
        cat "${sig_file}"
        echo "::endgroup::"

        # return signature file
