name: "GPG Sign"
description: "Use GPG to sign some artifacts"
author: chevdor
branding:
  icon: "umbrella"
  color: "blue"

inputs:
  key:
    description: >
      GPG Private Key
    required: true

  file:
    description: >
      The file to sign
    required: true

outputs:
  signature:
    description: >
      The detached signature, ascii armored
    value: ${{ steps.gpg_sign.outputs.signature }}

  sig_file:
    description: >
      The path of the signature file
    value: ${{ steps.gpg_sign.outputs.sig_file }}

runs:
  using: "composite"
  steps:
    - name: Install Tooling
      shell: bash
      run: |
        gpg --version

    - name: GPG Sign Artifact
      id: gpg_sign
      shell: bash
      env:
        GPG_PRIVATE_KEY: ${{ inputs.key }}
        FILE: ${{ inputs.file }}
      run: |

        # import private key
        echo "::group::Import Key"
        echo "Import private key"
        echo "$GPG_PRIVATE_KEY" | gpg --import

        # show list of keys
        echo "Show keys"
        gpg -K
        gpg --armor --export
        echo "::endgroup::"

        # sign artifact
        echo "::group::Signature of ${FILE}"
        echo "Sign artifact"
        gpg --detach-sig --armor "${FILE}"

        # show signature
        echo "GPG Signature"
        sig_file="${FILE}.asc"
        echo "Signature file: ${sig_file}"
        sig=$(cat "${sig_file}")
        echo "${sig}"

        echo "sig_file=${sig_file}" >> $GITHUB_OUTPUT
        echo "signature=${sig}" >> $GITHUB_OUTPUT

        echo "::endgroup::"

        # return signature file
