name: "GPG Sign"
description: "Use GPG to sign some artifacts"
author: chevdor
branding:
  icon: "umbrella"
  color: "blue"

inputs:
  key:
    description: >
      GPG Private Key
    required: true

  file:
    description: >
      The file to sign
    required: true

# outputs:
  # json:
  #   description: >
  #     Bla
    # value: ${{ steps.build.outputs.json }}

runs:
  using: "composite"
  steps:
    - name: Install Tooling
      shell: bash
      run: |
        gpg --version

    - name: GPG Sign Artifact
      id: gpg_sign
      shell: bash
      env:
        GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      run: |

        echo "TEST"

        # import private key
        echo "Import private key"
        echo "$GPG_PRIVATE_KEY" | gpg --import

        # show list of keys
        echo "Show keys"

        # sign artifact
        echo "Sign artifact"

        # show signature
        echo "Show signature"

        echo "::group::Debug"
        echo "foo=bar" >> $GITHUB_ENV
        echo "::endgroup::"

        # return signature file
